# -------------------------------------------------------------
# Function: evaluate_control_mode.R
# Part of the Model Predictive Control in buildings repository
# Developed by Roberto Garay Martinez
# -------------------------------------------------------------
# This function evaluates the optimality of a control mode sequence
# over a particular period.
# This is a wrapper function that allows to integrate an optimizer with
# a simulation code in "period_calculation".
# It performs the following steps:
#   1. Decodes the control modes from binary encoding
#   2. Converts the control modes to setpoints with histeresis
#   3. Calls the period_calculation function to simulate the building
#      and energy system operation over the period
#   4. Sums-up the reward over the period
# -------------------------------------------------------------
# INPUT:
# period_chunk: Data frame containing the data for the period to evaluate
# setpoint_modes: Data frame containing the mapping between modes and setpoints
# setpoint_modes_actual: Vector containing the binary encoding of the modes to be evaluated
#     This vector is automatically generated by the optimizer.
# parameters: List containing the model parameters to be passed-on to the simulator.
# Deadband: Numeric value defining the deadband for histeresis controllers
# periods_target: Vector of timestamps for the target period
# -------------------------------------------------------------
evaluate_control_mode <- function(period_chunk,
                                  setpoint_modes,
                                  setpoint_modes_actual,
                                  parameters,
                                  Deadband,
                                  periods_target) {
  
  # Defines the setpoint mode for market period
  # Takes the vector "setpoint_modes_actual" (binary encoded)
  # Encodes the binary vector for each "mode"
  # Then selects the maximum mode for each period
  {
    set_point_df <- data.frame(period = periods_target)
    n_periods <- nrow(set_point_df)
    n_modes <- length(unique(setpoint_modes$mode))
    
    for (i in seq_len(n_modes)) {
      set_point_df[[paste0("mode_", i)]] <-
        setpoint_modes_actual[((i-1)*n_periods + 1):(i*n_periods)]
    }
    
    mode_cols <- setdiff(colnames(set_point_df), "period")
    
    # Calculate maxmode
    set_point_df$maxmode <- apply(set_point_df[, mode_cols],
                                  1,
                                  function(x) {
                                    if (all(is.na(x)) || sum(x, na.rm = TRUE) == 0) {
                                      return(1)  # modo por defecto
                                      } else {
                                        idx <- which.max(x)
                                        return(as.numeric(sub("mode_", "", mode_cols[idx])))
                                      }
                                    }
                                  )
    # Reduce the dataframe
    set_point_df <- set_point_df[, c("period", "maxmode")]
  }
  
  # Conversion of modes to setpoints and thresholds for histeresis controllers
  {
    set_point_df <- convert_modes_to_setpoints(setpoint_modes_df = set_point_df,
                                               setpoint_modes    = setpoint_modes,
                                               Deadband          = Deadband,
                                               periods_target    = periods_target
                                               )
  }
  
  # Calculate the evolution of the building and the energy system
  period_chunk <- period_calculation(period_chunk, set_point_df, parameters)
  
  # Calculate reward
  reward <- sum(period_chunk$reward)
  
  # Take reward as output for the GA optimization
  return(reward)
}
