#!/bin/bash
# -------------------------------------------------------------
# scc_settings.sh
# SCC cluster settings for parametric MPC simulations.
# Generated by: 20_GUI/02_Configure_Parametric_Simulations/GUI_parametric.R
# Do not edit manually - use the GUI to regenerate.
# -------------------------------------------------------------

# Number of tasks (configurations) per Slurm job array.
# Most clusters impose a limit on array size (e.g. 1000).
# Adjust this value to match your cluster's limit.
TASKS_PER_JOB=500

# Slurm job name for identification in squeue.
JOB_NAME="MPC5_1"

# Slurm partition (queue) for job submission.
SCC_QUEUE="general"

# Slurm Quality of Service (qos) for job submission.
SCC_QOS="serial"

# User email for Slurm --mail-user notifications.
SCC_USER="roberto.garay@deusto.es"

# Cluster login username for squeue monitoring.
SCC_USERNAME="robgaray"

# Output file formats: individual flags for Main_df and
# Sinthetized_df_computed in CSV and/or RDS format.
SCC_OUTPUT_FORMATS="synth_csv,synth_rds"

# Whether to keep Slurm .err and .out log files (1=keep, 0=delete).
SCC_KEEP_LOGS=0

# Maximum number of automatic re-queue attempts for failed configurations.
SCC_MAX_REQUEUE=2
