# -------------------------------------------------------------
# Function: save_optim_params
# Part of the Model Predictive Control in buildings repository
# https://github.com/robgaray/Model-Predictive-Control-in-Buildings
# Developed by Roberto Garay Martinez
# -------------------------------------------------------------
# Saves the Optim_parameters.csv, scc_settings.sh, and
# Extraction_code.txt files to the 31_SCC_Simulation
# directory.
#
# Both files are written in binary mode with LF line endings so
# the generated files are compatible with Linux even when this
# function is run on Windows.
# -------------------------------------------------------------
# Inputs
#   df             : data.frame of configurations to save
#   scc_path       : path to the 31_SCC_Simulation directory
#   tasks_per_job  : integer, number of tasks (configurations)
#                    per Slurm job array submission
#   scc_queue      : character, Slurm partition name
#   scc_qos        : character, Slurm Quality of Service name
#   scc_user       : character, user email for --mail-user
#   scc_username   : character, cluster login username for squeue
#   output_formats : character vector, subset of
#                    c("main_csv","main_rds","synth_csv","synth_rds")
#   job_name       : character, Slurm job name for identification
#   keep_logs      : integer (1 or 0), whether to keep Slurm .err/.out files
#   max_requeue    : integer >= 0, maximum automatic re-queue attempts
# -------------------------------------------------------------
# Outputs
#   Invisible list with csv_path, sh_path, and ext_path of
#   written files.
# -------------------------------------------------------------
# Code outline
#   1. Sanitize inputs
#   2. Write Optim_parameters.csv
#   3. Write scc_settings.sh
#   4. Write Extraction_code.txt
# -------------------------------------------------------------
# Usage instructions
#   save_optim_params(df, scc_path, tasks_per_job = 100,
#                     job_name = "MPC_optim")
# -------------------------------------------------------------
# Where this function/script is used
#   Called by GUI_parametric.R when the user clicks
#   "Generate Configuration File".
# -------------------------------------------------------------
# functions/scripts called
#   None (base R only).
# -------------------------------------------------------------
save_optim_params <- function(df, scc_path, tasks_per_job,
                              scc_queue = "general", scc_qos = "serial",
                              scc_user = "",
                              scc_username = "",
                              output_formats = c("main_csv", "main_rds",
                                                 "synth_csv", "synth_rds"),
                              job_name = "MPC_optim",
                              keep_logs = 1L,
                              max_requeue = 2L) {

  # -------------------------------------------------------------
  # 1. Sanitize inputs to prevent shell injection
  # -------------------------------------------------------------
  {
    scc_queue      <- gsub('[^A-Za-z0-9_-]', '', scc_queue)
    scc_qos        <- gsub('[^A-Za-z0-9_-]', '', scc_qos)
    scc_user       <- gsub('[^A-Za-z0-9_.@-]', '', scc_user)
    scc_username   <- gsub('[^A-Za-z0-9_.-]', '', scc_username)
    job_name       <- gsub('[^A-Za-z0-9_.-]', '', job_name)
    if (!nzchar(job_name)) job_name <- "MPC_optim"
    output_formats <- intersect(output_formats,
                               c("main_csv", "main_rds",
                                 "synth_csv", "synth_rds"))
    keep_logs   <- as.integer(keep_logs)
    if (is.na(keep_logs) || !keep_logs %in% c(0L, 1L)) keep_logs <- 1L
    max_requeue <- as.integer(max_requeue)
    if (is.na(max_requeue) || max_requeue < 0) max_requeue <- 2L
  }

  # -------------------------------------------------------------
  # 2. Write Optim_parameters.csv with LF line endings
  # -------------------------------------------------------------
  {
    csv_path <- file.path(scc_path, "Optim_parameters.csv")
    tc <- textConnection("csv_lines", "w")
    write.csv(df, tc, row.names = FALSE, quote = FALSE)
    close(tc)
    con <- file(csv_path, open = "wb")
    writeLines(csv_lines, con, sep = "\n")
    close(con)
  }

  # -------------------------------------------------------------
  # 3. Write scc_settings.sh with cluster settings
  # -------------------------------------------------------------
  {
    sh_path  <- file.path(scc_path, "scc_settings.sh")
    sh_lines <- c(
      "#!/bin/bash",
      "# -------------------------------------------------------------",
      "# scc_settings.sh",
      "# SCC cluster settings for parametric MPC simulations.",
      paste0("# Generated by: 20_GUI/02_Configure_Parametric_Simulations/",
             "GUI_parametric.R"),
      "# Do not edit manually - use the GUI to regenerate.",
      "# -------------------------------------------------------------",
      "",
      "# Number of tasks (configurations) per Slurm job array.",
      "# Most clusters impose a limit on array size (e.g. 1000).",
      "# Adjust this value to match your cluster's limit.",
      paste0("TASKS_PER_JOB=", as.integer(tasks_per_job)),
      "",
      "# Slurm job name for identification in squeue.",
      paste0('JOB_NAME="', job_name, '"'),
      "",
      "# Slurm partition (queue) for job submission.",
      paste0('SCC_QUEUE="', scc_queue, '"'),
      "",
      "# Slurm Quality of Service (qos) for job submission.",
      paste0('SCC_QOS="', scc_qos, '"'),
      "",
      "# User email for Slurm --mail-user notifications.",
      paste0('SCC_USER="', scc_user, '"'),
      "",
      "# Cluster login username for squeue monitoring.",
      paste0('SCC_USERNAME="', scc_username, '"'),
      "",
      "# Output file formats: individual flags for Main_df and",
      "# Sinthetized_df_computed in CSV and/or RDS format.",
      paste0('SCC_OUTPUT_FORMATS="',
             paste(output_formats, collapse = ","), '"'),
      "",
      "# Whether to keep Slurm .err and .out log files (1=keep, 0=delete).",
      paste0("SCC_KEEP_LOGS=", keep_logs),
      "",
      "# Maximum number of automatic re-queue attempts for failed configurations.",
      paste0("SCC_MAX_REQUEUE=", max_requeue)
    )
    con <- file(sh_path, open = "wb")
    writeLines(sh_lines, con, sep = "\n")
    close(con)
  }

  # -------------------------------------------------------------
  # 4. Write Extraction_code.txt with LF line endings
  # Copies simulation results and logs from /scratch to /dipc.
  # Works regardless of the user's current directory.
  # -------------------------------------------------------------
  {
    ext_path  <- file.path(scc_path, "Extraction_code.txt")
    ext_lines <- c(
      '#!/bin/bash',
      '# -------------------------------------------------------------',
      '# Console script: Extraction_code.txt',
      '# Part of the Model Predictive Control in buildings repository',
      '# https://github.com/robgaray/Model-Predictive-Control-in-Buildings_WORK4',
      '# Developed by Roberto Garay Martinez',
      '# -------------------------------------------------------------',
      '# Location: 31_SCC_Simulation/Extraction_code.txt',
      '# -------------------------------------------------------------',
      '# Copies simulation results and logs from /scratch to /dipc.',
      '# Generated by: 20_GUI/02_Configure_Parametric_Simulations/GUI_parametric.R',
      '# Works regardless of the user\'s current directory.',
      '# -------------------------------------------------------------',
      '# Usage:',
      '#   bash "31_SCC_Simulation/Extraction_code.txt"',
      '#   # or from any directory:',
      '#   bash "/scratch/<USERNAME>/<JOB_NAME>/31_SCC_Simulation/Extraction_code.txt"',
      '# -------------------------------------------------------------',
      '',
      '# --- 1. Resolve script location to find project root --------------',
      'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
      'PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"',
      '',
      '# --- Convert DOS (CRLF) to Unix (LF) line endings ---------------',
      'sed -i \'s/\\r$//\' "${SCRIPT_DIR}/Extraction_code.txt" 2>/dev/null',
      '[[ -f "${SCRIPT_DIR}/scc_settings.sh" ]] && sed -i \'s/\\r$//\' "${SCRIPT_DIR}/scc_settings.sh"',
      '',
      '# --- 2. Load SCC settings -----------------------------------------',
      'SCC_SETTINGS="${SCRIPT_DIR}/scc_settings.sh"',
      'if [[ -f "$SCC_SETTINGS" ]]; then',
      '  source "$SCC_SETTINGS"',
      'else',
      '  echo "Warning: $SCC_SETTINGS not found. Using defaults."',
      paste0('  JOB_NAME="', job_name, '"'),
      paste0('  SCC_USERNAME="', scc_username, '"'),
      'fi',
      '',
      paste0(': "${JOB_NAME:=', job_name, '}"'),
      paste0(': "${SCC_USERNAME:=', scc_username, '}"'),
      '',
      'DIPC_USER="${SCC_USERNAME:-$USER}"',
      '',
      '# --- 3. Build source and destination paths -------------------------',
      'SRC_DIR="/scratch/${DIPC_USER}/${JOB_NAME}"',
      'DST_DIR="/dipc/${DIPC_USER}/${JOB_NAME}"',
      '',
      'echo "==================================="',
      'echo "Extraction started at $(date)"',
      'echo "Source (scratch): $SRC_DIR"',
      'echo "Destination (dipc): $DST_DIR"',
      'echo "==================================="',
      '',
      'if [[ ! -d "$SRC_DIR" ]]; then',
      '  echo "Error: Source directory does not exist: $SRC_DIR" >&2',
      '  exit 1',
      'fi',
      '',
      '# --- 4. Copy logs ---------------------------------------------------',
      'echo ""',
      'echo "--- Copying logs ---"',
      'if [[ -d "${SRC_DIR}/logs" ]]; then',
      '  mkdir -p "${DST_DIR}/logs"',
      '  rsync -av "${SRC_DIR}/logs/" "${DST_DIR}/logs/"',
      '  echo "Logs copied successfully."',
      'else',
      '  echo "No logs directory found in $SRC_DIR"',
      'fi',
      '',
      '# --- 5. Copy simulation output files --------------------------------',
      'echo ""',
      'echo "--- Copying simulation results ---"',
      'SRC_OUTPUT="${SRC_DIR}/30_Simulation/90_Output"',
      'DST_OUTPUT="${DST_DIR}/30_Simulation/90_Output"',
      'if [[ -d "$SRC_OUTPUT" ]]; then',
      '  mkdir -p "$DST_OUTPUT"',
      '  rsync -av "${SRC_OUTPUT}/" "${DST_OUTPUT}/"',
      '  echo "Simulation results copied successfully."',
      'else',
      '  echo "No output directory found: $SRC_OUTPUT"',
      'fi',
      '',
      '# --- 6. Copy job tracker --------------------------------------------',
      'echo ""',
      'echo "--- Copying job tracker ---"',
      'SRC_TRACKER="${SRC_DIR}/31_SCC_Simulation/job_tracker.csv"',
      'DST_SCC_DIR="${DST_DIR}/31_SCC_Simulation"',
      'if [[ -f "$SRC_TRACKER" ]]; then',
      '  mkdir -p "$DST_SCC_DIR"',
      '  cp -v "$SRC_TRACKER" "${DST_SCC_DIR}/job_tracker.csv"',
      '  echo "Job tracker copied."',
      'else',
      '  echo "No job tracker found: $SRC_TRACKER"',
      'fi',
      '',
      '# --- 7. Copy verification backups (if they exist) -------------------',
      'echo ""',
      'echo "--- Copying verification backups ---"',
      'BACKUPS_FOUND=0',
      'for bak in "${SRC_DIR}/31_SCC_Simulation/Optim_parameters_backup_"*.csv; do',
      '  if [[ -f "$bak" ]]; then',
      '    mkdir -p "$DST_SCC_DIR"',
      '    cp -v "$bak" "${DST_SCC_DIR}/"',
      '    BACKUPS_FOUND=$(( BACKUPS_FOUND + 1 ))',
      '  fi',
      'done',
      'if [[ "$BACKUPS_FOUND" -eq 0 ]]; then',
      '  echo "No verification backup files found."',
      'else',
      '  echo "$BACKUPS_FOUND backup file(s) copied."',
      'fi',
      '',
      '# --- 8. Summary ------------------------------------------------------',
      'echo ""',
      'echo "==================================="',
      'echo "Extraction completed at $(date)"',
      'echo "Results are available at: $DST_DIR"',
      'echo "==================================="'
    )
    con <- file(ext_path, open = "wb")
    writeLines(ext_lines, con, sep = "\n")
    close(con)
  }

  invisible(list(csv_path = csv_path, sh_path = sh_path,
                 ext_path = ext_path))
}
