# -------------------------------------------------------------
# Script: economic_analysis_setup.R
# Part of the Model Predictive Control in buildings repository
# https://github.com/robgaray/Model-Predictive-Control-in-Buildings
# Developed by Roberto Garay Martinez
# -------------------------------------------------------------
# Overall description
# Builds the empty skeleton of the economic analysis output, a named
# list called analysis with two data frames, market and slot. The
# market-decision flows are accumulated into them during the
# simulation loop by integrate_market_process.R; the execution-phase
# flows and every derived fraction are filled in at the end by
# economic_analysis_finalize.R. Together the two tables give the global
# economic picture that the individual commitment/price matrices
# (market_commitments, full_market_information) do not provide on
# their own: those hold quantities, prices and costs per market event
# and future step, but nothing that adds up to "what did this market
# do, in total" or "what happened in this slot, in total".
# -------------------------------------------------------------
# economic_analysis$market - one row per market
# There is one row for every Scheduling market event, one row for
# every Piloting market event, and one row per market slot for
# Execution (Execution is not a market, so it is reported at the
# resolution at which it actually happens, one delivery slot at a
# time). Rows are ordered by time, and within the same timestamp by
# Scheduling, then Piloting, then Execution.
# Columns 4-12 hold the total (summed) value over all the slots on
# which that market operated.
# -------------------------------------------------------------
# economic_analysis$slot - one row per market slot
# One row per MarketUTC interval of the simulation, holding the
# energy actually delivered in that slot and the breakdown of how the
# position for that slot was built up across the markets that traded
# it.
# -------------------------------------------------------------
# Slot-to-market attribution when markets overlap
# A single slot is traded many times: by the Scheduling markets that
# cover it, by the Piloting markets that cover it, and finally at
# Execution. When more than one market clears at the same timestamp,
# each slot is attributed to exactly one of them, as follows:
#   - If a Scheduling market clears at that timestamp and the slot is
#     inside its control horizon, the slot is attributed to that
#     Scheduling market - whether the energy/economic flow was
#     generated by the Scheduling decision or by the Piloting decision
#     that cleared at the same timestamp.
#   - The slot being delivered is attributed to Execution, which is
#     what the Execution rows report.
#   - Every remaining slot is attributed to the Piloting market.
# -------------------------------------------------------------
# Inputs
#   Main_df    : Data frame. Must already carry MarketUTC and the
#                Sched_*/Pilot_* market timeline columns (i.e. this
#                script runs after market_columns_setup.R).
#   parameters : Named list. Only parameters$debug_and_config$verbose
#                is read, to gate the console summary at the end.
# -------------------------------------------------------------
# Outputs
#   analysis : Named list of 3 elements (market, slot, index), with
#              every accumulator column of market/slot initialised to
#              0. market and slot are the two data frames that make up
#              the final output; index is working row-lookup state,
#              dropped by economic_analysis_finalize.R before export - see
#              block 5 below.
# -------------------------------------------------------------
# Code outline
# 1. Market slots of the simulation
# 2. Row set of economic_analysis$market (Scheduling, Piloting, Execution)
# 3. Initialise economic_analysis$market accumulators
# 4. Initialise economic_analysis$slot accumulators
# 5. Row lookup index
# -------------------------------------------------------------
# Usage
# source(file.path("30_Simulation", "04_Scripts", "economic_analysis_setup.R"))
# -------------------------------------------------------------
# Where this script is used
# Sourced by Main.R, after market_commitments_setup.R and before
# the simulation loop.
# -------------------------------------------------------------
# functions/scripts called
# is_market_active()
# -------------------------------------------------------------

# -------------------------------------------------------------
# 1. Market slots of the simulation
# -------------------------------------------------------------
{
  if (!"MarketUTC" %in% names(Main_df)) {
    stop("economic_analysis_setup.R: Main_df$MarketUTC is required. This script ",
         "must run after market_columns_setup.R.")
  }

  analysis_slot_time <- sort(unique(Main_df$MarketUTC))
  n_analysis_slot    <- length(analysis_slot_time)
}

# -------------------------------------------------------------
# 2. Row set of economic_analysis$market
# -------------------------------------------------------------
# is_market_active is called per row to find the MarketUTC intervals
# where a Scheduling or a Piloting market actually clears, so that one
# row is created per real market event rather than per interval. The
# market name of each event is taken from the same Main_df row, so the
# naming matches the rest of the project (DA, ID1, cID1, ...).
# -------------------------------------------------------------
{
  sched_active <- sapply(Main_df$Sched_Market_Name, is_market_active)
  pilot_active <- sapply(Main_df$Pilot_Market_Name, is_market_active)

  sched_events <- Main_df[sched_active, c("MarketUTC", "Sched_Market_Name")]
  sched_events <- sched_events[!duplicated(sched_events$MarketUTC), ]

  pilot_events <- Main_df[pilot_active, c("MarketUTC", "Pilot_Market_Name")]
  pilot_events <- pilot_events[!duplicated(pilot_events$MarketUTC), ]

  analysis_market_time <- c(
    sched_events$MarketUTC,
    pilot_events$MarketUTC,
    analysis_slot_time
  )
  analysis_market_name <- c(
    as.character(sched_events$Sched_Market_Name),
    as.character(pilot_events$Pilot_Market_Name),
    rep("EXEC", n_analysis_slot)
  )
  analysis_market_type <- c(
    rep("Scheduling", nrow(sched_events)),
    rep("Piloting",   nrow(pilot_events)),
    rep("Execution",  n_analysis_slot)
  )

  # Ordered by time, and within one timestamp by Scheduling (1),
  # Piloting (2), Execution (3), matching the reporting order the
  # tables are meant to be read in.
  type_rank     <- match(analysis_market_type, c("Scheduling", "Piloting", "Execution"))
  analysis_order <- order(analysis_market_time, type_rank)

  analysis_market_time <- analysis_market_time[analysis_order]
  analysis_market_name <- analysis_market_name[analysis_order]
  analysis_market_type <- analysis_market_type[analysis_order]

  rm(sched_active, pilot_active, sched_events, pilot_events,
     type_rank, analysis_order)
}

# -------------------------------------------------------------
# 3. Initialise economic_analysis$market accumulators
# -------------------------------------------------------------
# Energy_* and Flex_* hold quantities (kWh, always >= 0); Cash_flow,
# PL_rebuy_resale, Flex_executed_cash_flow and Distribution_cost hold
# money, and share the same sign convention as every other economic
# signal in the repository: positive means money received (income),
# negative means money paid (expense) - see
# 00_Agent_Input/20260818_comentarios_observaciones_anteriores.md.
# Distribution_cost is consequently always <= 0 (it is only ever an
# expense); it comes straight from Main_df$Elec_cost_distr_h, which
# already carries that sign (see implement_control_step.R).
# PL_rebuy_resale is the net cash flow of the unwinding operations
# alone (resale revenue plus flexibility resale revenue, minus buyback
# cost plus flexibility buyback cost), valued at the prices of the
# market that performed them.
# The last three columns only apply to Execution rows and are left at
# NA on Scheduling and Piloting rows.
# -------------------------------------------------------------
{
  is_execution_row <- analysis_market_type == "Execution"
  na_unless_exec   <- ifelse(is_execution_row, 0, NA_real_)

  economic_analysis <- list()

  economic_analysis$market <- data.frame(
    time                    = analysis_market_time,
    market_name             = analysis_market_name,
    market_type             = analysis_market_type,
    Energy_bought           = 0,
    Energy_rebought         = 0,
    Energy_sold             = 0,
    Energy_resold           = 0,
    Flex_up_sold            = 0,
    Flex_up_rebought        = 0,
    Flex_down_sold          = 0,
    Flex_down_rebought      = 0,
    Cash_flow               = 0,
    PL_rebuy_resale         = 0,
    Flex_executed           = na_unless_exec,
    Flex_executed_cash_flow = na_unless_exec,
    Distribution_cost       = na_unless_exec,
    stringsAsFactors        = FALSE
  )

  rm(is_execution_row, na_unless_exec,
     analysis_market_time, analysis_market_name, analysis_market_type)
}

# -------------------------------------------------------------
# 4. Initialise economic_analysis$slot accumulators
# -------------------------------------------------------------
# The Qty_*/Val_* columns are working accumulators: they are filled
# during the simulation loop and consumed by economic_analysis_finalize.R to
# derive the reported fractions, which cannot be accumulated directly
# because their denominators are only known once the simulation is
# over. They are dropped from the final table.
# Cost_energy_bought and Revenue_energy_sold keep the two directions
# apart so each can be reported on its own, but each already nets its
# own unwinding operations: a resale is an avoided cost and reduces
# Cost_energy_bought, a rebuy is an avoided revenue and reduces
# Revenue_energy_sold (see accumulate_market_operation()'s header).
# They are therefore magnitudes of a single direction, not of a single
# sign: a slot whose position was mostly unwound reports a negative
# cost or a negative revenue. Cost_energy_bought counts money paid as
# positive, so the reported cost of a slot is its negative (see
# data_outputs.R); Revenue_energy_sold, Revenue_flex_commitments and
# Cash_flow are signed like every other economic signal (positive =
# income). Distribution_cost is likewise signed (always <= 0, an
# expense only) - see economic_analysis$market's own note on this above.
# -------------------------------------------------------------
{
  economic_analysis$slot <- data.frame(
    time                     = analysis_slot_time,
    Energy_in                = 0,
    Energy_out               = 0,
    Frac_scheduling          = 0,
    Frac_rebuy_resale        = 0,
    Frac_execution           = 0,
    Flex_committed           = 0,
    Frac_flex_rebuy          = 0,
    Flex_down_committed      = 0,
    Cost_energy_bought       = 0,
    Revenue_energy_sold      = 0,
    Distribution_cost        = 0,
    Revenue_flex_commitments = 0,
    Cash_flow                = 0,
    Frac_rebuy_resale_value  = 0,
    Qty_scheduling           = 0,
    Qty_rebuy_resale         = 0,
    Qty_execution            = 0,
    Qty_flex_rebought        = 0,
    Val_rebuy_resale         = 0,
    stringsAsFactors         = FALSE
  )

  rm(analysis_slot_time, n_analysis_slot)
}

# -------------------------------------------------------------
# 5. Row lookup index
# -------------------------------------------------------------
# economic_analysis$index holds the row-resolution helpers the simulation loop
# needs to add a flow to the right row without searching the tables
# every time. slot_key is the numeric form of economic_analysis$slot$time, so a
# whole market's target slots can be located with a single match();
# row_sched/row_pilot/row_exec then map each slot position to the row
# of economic_analysis$market that reports it (NA when no market of that type
# clears at that slot). This sub-list is working state, not output:
# economic_analysis_finalize.R drops it before the results are exported.
# -------------------------------------------------------------
{
  slot_key <- as.numeric(economic_analysis$slot$time)

  market_key  <- as.numeric(economic_analysis$market$time)
  market_rows <- seq_len(nrow(economic_analysis$market))

  economic_analysis$index <- list(
    slot_key  = slot_key,
    row_sched = market_rows[match(
      paste0(slot_key, "|Scheduling"),
      paste0(market_key, "|", economic_analysis$market$market_type)
    )],
    row_pilot = market_rows[match(
      paste0(slot_key, "|Piloting"),
      paste0(market_key, "|", economic_analysis$market$market_type)
    )],
    row_exec  = market_rows[match(
      paste0(slot_key, "|Execution"),
      paste0(market_key, "|", economic_analysis$market$market_type)
    )]
  )

  if (parameters$debug_and_config$verbose) {
    cat("economic_analysis initialised:", nrow(economic_analysis$market), "market rows,",
        nrow(economic_analysis$slot), "slot rows\n")
  }

  rm(slot_key, market_key, market_rows)
}
